spring:
  application:
    name: snoozy-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_URI}
              predicates:
                - Path=/api/v1/auth/**
            - id: user-service
              uri: ${USER_URI}
              predicates:
                - Path=/api/v1/users/**,/api/v1/friends/**
              filters:
                - JwtAuthenticationFilterGateway
            - id: group-service
              uri: ${GROUP_URI}
              predicates:
                - Path=/api/v1/groups/**
              filters:
                - JwtAuthenticationFilterGateway
            - id: file-service
              uri: ${FILE_URI}
              predicates:
                - Path=/api/v1/files/**
            - id: alarm-service
              uri: ${ALARM_URI}
              predicates:
                - Path=/api/v1/alarms/**
              filters:
                - JwtAuthenticationFilterGateway
jwt:
  secret-token: ${JWT_SECRET_TOKEN}